package com.yutian.lucene.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HotelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public HotelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLkNameIsNull() {
			addCriterion("lk_name is null");
			return (Criteria) this;
		}

		public Criteria andLkNameIsNotNull() {
			addCriterion("lk_name is not null");
			return (Criteria) this;
		}

		public Criteria andLkNameEqualTo(String value) {
			addCriterion("lk_name =", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameNotEqualTo(String value) {
			addCriterion("lk_name <>", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameGreaterThan(String value) {
			addCriterion("lk_name >", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameGreaterThanOrEqualTo(String value) {
			addCriterion("lk_name >=", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameLessThan(String value) {
			addCriterion("lk_name <", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameLessThanOrEqualTo(String value) {
			addCriterion("lk_name <=", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameLike(String value) {
			addCriterion("lk_name like", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameNotLike(String value) {
			addCriterion("lk_name not like", value, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameIn(List<String> values) {
			addCriterion("lk_name in", values, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameNotIn(List<String> values) {
			addCriterion("lk_name not in", values, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameBetween(String value1, String value2) {
			addCriterion("lk_name between", value1, value2, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkNameNotBetween(String value1, String value2) {
			addCriterion("lk_name not between", value1, value2, "lkName");
			return (Criteria) this;
		}

		public Criteria andLkSexIsNull() {
			addCriterion("lk_sex is null");
			return (Criteria) this;
		}

		public Criteria andLkSexIsNotNull() {
			addCriterion("lk_sex is not null");
			return (Criteria) this;
		}

		public Criteria andLkSexEqualTo(String value) {
			addCriterion("lk_sex =", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexNotEqualTo(String value) {
			addCriterion("lk_sex <>", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexGreaterThan(String value) {
			addCriterion("lk_sex >", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexGreaterThanOrEqualTo(String value) {
			addCriterion("lk_sex >=", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexLessThan(String value) {
			addCriterion("lk_sex <", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexLessThanOrEqualTo(String value) {
			addCriterion("lk_sex <=", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexLike(String value) {
			addCriterion("lk_sex like", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexNotLike(String value) {
			addCriterion("lk_sex not like", value, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexIn(List<String> values) {
			addCriterion("lk_sex in", values, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexNotIn(List<String> values) {
			addCriterion("lk_sex not in", values, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexBetween(String value1, String value2) {
			addCriterion("lk_sex between", value1, value2, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkSexNotBetween(String value1, String value2) {
			addCriterion("lk_sex not between", value1, value2, "lkSex");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeIsNull() {
			addCriterion("lk_idcode is null");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeIsNotNull() {
			addCriterion("lk_idcode is not null");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeEqualTo(String value) {
			addCriterion("lk_idcode =", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeNotEqualTo(String value) {
			addCriterion("lk_idcode <>", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeGreaterThan(String value) {
			addCriterion("lk_idcode >", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeGreaterThanOrEqualTo(String value) {
			addCriterion("lk_idcode >=", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeLessThan(String value) {
			addCriterion("lk_idcode <", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeLessThanOrEqualTo(String value) {
			addCriterion("lk_idcode <=", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeLike(String value) {
			addCriterion("lk_idcode like", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeNotLike(String value) {
			addCriterion("lk_idcode not like", value, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeIn(List<String> values) {
			addCriterion("lk_idcode in", values, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeNotIn(List<String> values) {
			addCriterion("lk_idcode not in", values, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeBetween(String value1, String value2) {
			addCriterion("lk_idcode between", value1, value2, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkIdCodeNotBetween(String value1, String value2) {
			addCriterion("lk_idcode not between", value1, value2, "lkIdCode");
			return (Criteria) this;
		}

		public Criteria andLkAddressIsNull() {
			addCriterion("lk_address is null");
			return (Criteria) this;
		}

		public Criteria andLkAddressIsNotNull() {
			addCriterion("lk_address is not null");
			return (Criteria) this;
		}

		public Criteria andLkAddressEqualTo(String value) {
			addCriterion("lk_address =", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressNotEqualTo(String value) {
			addCriterion("lk_address <>", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressGreaterThan(String value) {
			addCriterion("lk_address >", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressGreaterThanOrEqualTo(String value) {
			addCriterion("lk_address >=", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressLessThan(String value) {
			addCriterion("lk_address <", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressLessThanOrEqualTo(String value) {
			addCriterion("lk_address <=", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressLike(String value) {
			addCriterion("lk_address like", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressNotLike(String value) {
			addCriterion("lk_address not like", value, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressIn(List<String> values) {
			addCriterion("lk_address in", values, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressNotIn(List<String> values) {
			addCriterion("lk_address not in", values, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressBetween(String value1, String value2) {
			addCriterion("lk_address between", value1, value2, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLkAddressNotBetween(String value1, String value2) {
			addCriterion("lk_address not between", value1, value2, "lkAddress");
			return (Criteria) this;
		}

		public Criteria andLgHNameIsNull() {
			addCriterion("lg_hname is null");
			return (Criteria) this;
		}

		public Criteria andLgHNameIsNotNull() {
			addCriterion("lg_hname is not null");
			return (Criteria) this;
		}

		public Criteria andLgHNameEqualTo(String value) {
			addCriterion("lg_hname =", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameNotEqualTo(String value) {
			addCriterion("lg_hname <>", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameGreaterThan(String value) {
			addCriterion("lg_hname >", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameGreaterThanOrEqualTo(String value) {
			addCriterion("lg_hname >=", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameLessThan(String value) {
			addCriterion("lg_hname <", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameLessThanOrEqualTo(String value) {
			addCriterion("lg_hname <=", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameLike(String value) {
			addCriterion("lg_hname like", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameNotLike(String value) {
			addCriterion("lg_hname not like", value, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameIn(List<String> values) {
			addCriterion("lg_hname in", values, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameNotIn(List<String> values) {
			addCriterion("lg_hname not in", values, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameBetween(String value1, String value2) {
			addCriterion("lg_hname between", value1, value2, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHNameNotBetween(String value1, String value2) {
			addCriterion("lg_hname not between", value1, value2, "lgHName");
			return (Criteria) this;
		}

		public Criteria andLgHAddressIsNull() {
			addCriterion("lg_haddress is null");
			return (Criteria) this;
		}

		public Criteria andLgHAddressIsNotNull() {
			addCriterion("lg_haddress is not null");
			return (Criteria) this;
		}

		public Criteria andLgHAddressEqualTo(String value) {
			addCriterion("lg_haddress =", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressNotEqualTo(String value) {
			addCriterion("lg_haddress <>", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressGreaterThan(String value) {
			addCriterion("lg_haddress >", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressGreaterThanOrEqualTo(String value) {
			addCriterion("lg_haddress >=", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressLessThan(String value) {
			addCriterion("lg_haddress <", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressLessThanOrEqualTo(String value) {
			addCriterion("lg_haddress <=", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressLike(String value) {
			addCriterion("lg_haddress like", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressNotLike(String value) {
			addCriterion("lg_haddress not like", value, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressIn(List<String> values) {
			addCriterion("lg_haddress in", values, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressNotIn(List<String> values) {
			addCriterion("lg_haddress not in", values, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressBetween(String value1, String value2) {
			addCriterion("lg_haddress between", value1, value2, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgHAddressNotBetween(String value1, String value2) {
			addCriterion("lg_haddress not between", value1, value2, "lgHAddress");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneIsNull() {
			addCriterion("lg_telphone is null");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneIsNotNull() {
			addCriterion("lg_telphone is not null");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneEqualTo(String value) {
			addCriterion("lg_telphone =", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneNotEqualTo(String value) {
			addCriterion("lg_telphone <>", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneGreaterThan(String value) {
			addCriterion("lg_telphone >", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneGreaterThanOrEqualTo(String value) {
			addCriterion("lg_telphone >=", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneLessThan(String value) {
			addCriterion("lg_telphone <", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneLessThanOrEqualTo(String value) {
			addCriterion("lg_telphone <=", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneLike(String value) {
			addCriterion("lg_telphone like", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneNotLike(String value) {
			addCriterion("lg_telphone not like", value, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneIn(List<String> values) {
			addCriterion("lg_telphone in", values, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneNotIn(List<String> values) {
			addCriterion("lg_telphone not in", values, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneBetween(String value1, String value2) {
			addCriterion("lg_telphone between", value1, value2, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLgTelphoneNotBetween(String value1, String value2) {
			addCriterion("lg_telphone not between", value1, value2, "lgTelphone");
			return (Criteria) this;
		}

		public Criteria andLkNoroomIsNull() {
			addCriterion("lk_noroom is null");
			return (Criteria) this;
		}

		public Criteria andLkNoroomIsNotNull() {
			addCriterion("lk_noroom is not null");
			return (Criteria) this;
		}

		public Criteria andLkNoroomEqualTo(String value) {
			addCriterion("lk_noroom =", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomNotEqualTo(String value) {
			addCriterion("lk_noroom <>", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomGreaterThan(String value) {
			addCriterion("lk_noroom >", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomGreaterThanOrEqualTo(String value) {
			addCriterion("lk_noroom >=", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomLessThan(String value) {
			addCriterion("lk_noroom <", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomLessThanOrEqualTo(String value) {
			addCriterion("lk_noroom <=", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomLike(String value) {
			addCriterion("lk_noroom like", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomNotLike(String value) {
			addCriterion("lk_noroom not like", value, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomIn(List<String> values) {
			addCriterion("lk_noroom in", values, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomNotIn(List<String> values) {
			addCriterion("lk_noroom not in", values, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomBetween(String value1, String value2) {
			addCriterion("lk_noroom between", value1, value2, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkNoroomNotBetween(String value1, String value2) {
			addCriterion("lk_noroom not between", value1, value2, "lkNoroom");
			return (Criteria) this;
		}

		public Criteria andLkLtimeIsNull() {
			addCriterion("lk_ltime is null");
			return (Criteria) this;
		}

		public Criteria andLkLtimeIsNotNull() {
			addCriterion("lk_ltime is not null");
			return (Criteria) this;
		}

		public Criteria andLkLtimeEqualTo(Date value) {
			addCriterion("lk_ltime =", value, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeNotEqualTo(Date value) {
			addCriterion("lk_ltime <>", value, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeGreaterThan(Date value) {
			addCriterion("lk_ltime >", value, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lk_ltime >=", value, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeLessThan(Date value) {
			addCriterion("lk_ltime <", value, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeLessThanOrEqualTo(Date value) {
			addCriterion("lk_ltime <=", value, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeIn(List<Date> values) {
			addCriterion("lk_ltime in", values, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeNotIn(List<Date> values) {
			addCriterion("lk_ltime not in", values, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeBetween(Date value1, Date value2) {
			addCriterion("lk_ltime between", value1, value2, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkLtimeNotBetween(Date value1, Date value2) {
			addCriterion("lk_ltime not between", value1, value2, "lkLtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeIsNull() {
			addCriterion("lk_etime is null");
			return (Criteria) this;
		}

		public Criteria andLkEtimeIsNotNull() {
			addCriterion("lk_etime is not null");
			return (Criteria) this;
		}

		public Criteria andLkEtimeEqualTo(Date value) {
			addCriterion("lk_etime =", value, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeNotEqualTo(Date value) {
			addCriterion("lk_etime <>", value, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeGreaterThan(Date value) {
			addCriterion("lk_etime >", value, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lk_etime >=", value, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeLessThan(Date value) {
			addCriterion("lk_etime <", value, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeLessThanOrEqualTo(Date value) {
			addCriterion("lk_etime <=", value, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeIn(List<Date> values) {
			addCriterion("lk_etime in", values, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeNotIn(List<Date> values) {
			addCriterion("lk_etime not in", values, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeBetween(Date value1, Date value2) {
			addCriterion("lk_etime between", value1, value2, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkEtimeNotBetween(Date value1, Date value2) {
			addCriterion("lk_etime not between", value1, value2, "lkEtime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeIsNull() {
			addCriterion("lk_createtime is null");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeIsNotNull() {
			addCriterion("lk_createtime is not null");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeEqualTo(Date value) {
			addCriterion("lk_createtime =", value, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeNotEqualTo(Date value) {
			addCriterion("lk_createtime <>", value, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeGreaterThan(Date value) {
			addCriterion("lk_createtime >", value, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("lk_createtime >=", value, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeLessThan(Date value) {
			addCriterion("lk_createtime <", value, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("lk_createtime <=", value, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeIn(List<Date> values) {
			addCriterion("lk_createtime in", values, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeNotIn(List<Date> values) {
			addCriterion("lk_createtime not in", values, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeBetween(Date value1, Date value2) {
			addCriterion("lk_createtime between", value1, value2, "lkCreatetime");
			return (Criteria) this;
		}

		public Criteria andLkCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("lk_createtime not between", value1, value2, "lkCreatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Hotel
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Hotel
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 26 22:21:53 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}