package com.yutian.lucene.entity;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Hotel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.id
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_name
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lkName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_sex
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lkSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_idcode
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lkIdCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_address
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lkAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lg_hname
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lgHName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lg_haddress
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lgHAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lg_telphone
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lgTelphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_noroom
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private String lkNoroom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_ltime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private Date lkLtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_etime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private Date lkEtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Hotel.lk_createtime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	private Date lkCreatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.id
	 * @return  the value of Hotel.id
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.id
	 * @param id  the value for Hotel.id
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_name
	 * @return  the value of Hotel.lk_name
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLkName() {
		return lkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_name
	 * @param lkName  the value for Hotel.lk_name
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkName(String lkName) {
		this.lkName = lkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_sex
	 * @return  the value of Hotel.lk_sex
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLkSex() {
		return lkSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_sex
	 * @param lkSex  the value for Hotel.lk_sex
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkSex(String lkSex) {
		this.lkSex = lkSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_idcode
	 * @return  the value of Hotel.lk_idcode
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLkIdCode() {
		return lkIdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_idcode
	 * @param lkIdCode  the value for Hotel.lk_idcode
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkIdCode(String lkIdCode) {
		this.lkIdCode = lkIdCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_address
	 * @return  the value of Hotel.lk_address
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLkAddress() {
		return lkAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_address
	 * @param lkAddress  the value for Hotel.lk_address
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkAddress(String lkAddress) {
		this.lkAddress = lkAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lg_hname
	 * @return  the value of Hotel.lg_hname
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLgHName() {
		return lgHName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lg_hname
	 * @param lgHName  the value for Hotel.lg_hname
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLgHName(String lgHName) {
		this.lgHName = lgHName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lg_haddress
	 * @return  the value of Hotel.lg_haddress
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLgHAddress() {
		return lgHAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lg_haddress
	 * @param lgHAddress  the value for Hotel.lg_haddress
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLgHAddress(String lgHAddress) {
		this.lgHAddress = lgHAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lg_telphone
	 * @return  the value of Hotel.lg_telphone
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLgTelphone() {
		return lgTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lg_telphone
	 * @param lgTelphone  the value for Hotel.lg_telphone
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLgTelphone(String lgTelphone) {
		this.lgTelphone = lgTelphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_noroom
	 * @return  the value of Hotel.lk_noroom
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public String getLkNoroom() {
		return lkNoroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_noroom
	 * @param lkNoroom  the value for Hotel.lk_noroom
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkNoroom(String lkNoroom) {
		this.lkNoroom = lkNoroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_ltime
	 * @return  the value of Hotel.lk_ltime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public Date getLkLtime() {
		return lkLtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_ltime
	 * @param lkLtime  the value for Hotel.lk_ltime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkLtime(Date lkLtime) {
		this.lkLtime = lkLtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_etime
	 * @return  the value of Hotel.lk_etime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public Date getLkEtime() {
		return lkEtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_etime
	 * @param lkEtime  the value for Hotel.lk_etime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkEtime(Date lkEtime) {
		this.lkEtime = lkEtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Hotel.lk_createtime
	 * @return  the value of Hotel.lk_createtime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public Date getLkCreatetime() {
		return lkCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Hotel.lk_createtime
	 * @param lkCreatetime  the value for Hotel.lk_createtime
	 * @mbg.generated  Thu Oct 26 22:22:48 CST 2017
	 */
	public void setLkCreatetime(Date lkCreatetime) {
		this.lkCreatetime = lkCreatetime;
	}
	
	@Override
	public String toString() {
		return new ToStringBuilder(this,ToStringStyle.MULTI_LINE_STYLE)
				.append("id:"+getId())
				.append("lkName:",getLkName())
				.append("lkIdCode",getLkIdCode())
				.append("lkLtime:",getLkLtime())
				.append("lkEtime:",getLkEtime())
				.append("lkNoroom:",getLkNoroom())
				.append("lgHName:",getLgHName())
				.append("lkCreatetime:",getLkCreatetime())
				.toString();
	}
	
	
}