package com.yutian.lucene.mapper;

import com.yutian.lucene.entity.Hotel;
import com.yutian.lucene.entity.HotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelMapper {
    
     
    long countByExample(HotelExample example);

    int deleteByExample(HotelExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Hotel record);

    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Hotel
     *
     * @mbg.generated Thu Oct 26 22:22:48 CST 2017
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Hotel
     *
     * @mbg.generated Thu Oct 26 22:22:48 CST 2017
     */
    Hotel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Hotel
     *
     * @mbg.generated Thu Oct 26 22:22:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Hotel
     *
     * @mbg.generated Thu Oct 26 22:22:48 CST 2017
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Hotel
     *
     * @mbg.generated Thu Oct 26 22:22:48 CST 2017
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Hotel
     *
     * @mbg.generated Thu Oct 26 22:22:48 CST 2017
     */
    int updateByPrimaryKey(Hotel record);
}